name: Server CI
on:
  pull_request:
    paths:
      - "packages/server/*"
  push:
    paths:
      - "packages/server/*"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: |
          cd packages/server
          yarn test --changedSince=main
